/**
 * DO NOT MODIFY THIS VARIABLE
 * THIS VARIABLE IS AUTO-GENERATED BY BUILD WORKFLOW
 */
const GIT_HASH = 'commitHash';

// you can modify these to your own repo for updater to check
const repo = {
    owner: 'wavedevgit',
    repo: 'wave2fa',
    // DO NOT MODIFY THIS LINE IT IS AUTO-GENERATED BY BUILD WORKFLOW
    branch: 'commitBranch',
};

export default GIT_HASH;
export { repo };
