/**
 * DO NOT MODIFY THESE VARIABLES
 * THIS VARIABLE IS AUTO-GENERATED BY BUILD WORKFLOW
 */
const GIT_HASH = 'commitHash';
const VERSION = 'wave2faVersion';

// you can modify these to your own repo for updater to check
const repo: { owner: string; repo: string; branch: string } = {
    owner: 'wavedevgit',
    repo: 'wave2fa-releases',
    // DO NOT MODIFY THIS LINE IT IS AUTO-GENERATED BY BUILD WORKFLOW
    branch: 'commitBranch',
};

export { GIT_HASH, VERSION };
export { repo };
