/**
 * DO NOT MODIFY THESE VARIABLES
 * THESE VARIABLE ARE AUTO-GENERATED BY RSPACK
 */
/** @ts-ignore **/
const GIT_HASH = __COMMIT__HASH__;
/** @ts-ignore **/
const VERSION = __VERSION__;

// you can modify these to your own repo for updater to check
const repo: { owner: string; repo: string; branch: string } = {
    owner: 'wavedevgit',
    repo: 'wave2fa-releases',
    // DO NOT MODIFY THIS LINE IT IS AUTO-GENERATED BY RSPACK
    /** @ts-ignore **/
    branch: __COMMIT__BRANCH__,
};

export { GIT_HASH, VERSION };
export { repo };
